### PR TITLE
Use state

### PR DESCRIPTION
**Pull request by mcwhittemore**
Converting the module to keep input values as state so to mitigate value shift caused by converting rgba into hsv.

### CODE REVIEW

**Comment by tristen** [comment]
Sweet! checking this out.

**Comment by tristen** [comment]
Approach wise this LGTM

Looks like alpha input may need to be hooked up to state too as it's faulting.

**Comment by mcwhittemore** [comment]
@tristen nice catch on the alpha input. It might be nice to have all the input's map to the same function as there is a lot of duplication of logic going on here. If that sounds good, I can either do that in this PR or another one.

**Comment by tristen** [comment]
@mcwhittemore Yeah ... passing all input through the same function is a good plan. I'd merge this and address that in a new pr.

**Comment by mcwhittemore** [comment]
Cool. I think this is just a patch bump.

**Comment by mcwhittemore** [comment]
@tristen & @tmcw,

So... it looks like moving colorpickr to do internal mgmt for the color values turns out to create invariant violations in some applications.

**Pull request merged**
