### PR TITLE
update to react 0.14 and babel 6.0

### PR DESCRIPTION
**Pull request by lilactown**
This is a pull request to update this package to react 0.14.x.

This pull request is dependent on `react-range` also updating to the latest version in it's `package.json`: https://github.com/mapbox/react-range/pull/9.

Once the above pull request is accepted I'll update this one with the appropriate `react-range` version.

### CODE REVIEW

**Comment by lilactown** [comment]
I also am updating to the latest version of babel (6.0). Should I create a new PR for that?

**Comment by tristen** [comment]
@Lokeh updating Babel in this PR sounds alright to me. Can you squash your changes into a single commit and cite the addition in the description of the commit message?

**Comment by tristen** [comment]
@Lokeh You good to fix the failing tests and rebase?

**Comment by tristen** [comment]
In with https://github.com/mapbox/react-colorpickr/commit/70d632cfeafa5e41a9bba935c85519bcba011ef4

**Pull request closed without merging**
